// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticOnline.Data.Context;

namespace StatisticOnline.Data.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20190112152107_StatisticOnline")]
    partial class StatisticOnline
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("StatisticOnline.Data.Models.StatisticOnlineDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountAll");

                    b.Property<int>("CountGuest");

                    b.Property<int>("CountRegistered");

                    b.Property<DateTime>("CurrenTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.ToTable("StatisticOnline");
                });
#pragma warning restore 612, 618
        }
    }
}
