/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./../../models/security";
import * as Mappers from "./../../models/security/mappers";
import * as operations from "./operations";
import { SecurityContext } from "./SecurityContext";

class Security extends SecurityContext {
  // Operation groups
  feature: operations.FeatureOperations;
  functions: operations.Functions;
  rights: operations.Rights;
  role: operations.RoleOperations;
  userRights: operations.UserRightsOperations;

  /**
   * Initializes a new instance of the Security class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.SecurityOptions) {
    super(options);
    this.feature = new operations.FeatureOperations(this);
    this.functions = new operations.Functions(this);
    this.rights = new operations.Rights(this);
    this.role = new operations.RoleOperations(this);
    this.userRights = new operations.UserRightsOperations(this);
  }
}

// Operation Specifications

export {
  Security,
  SecurityContext,
  Models as SecurityModels,
  Mappers as SecurityMappers
};
export * from "./operations";
