/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const AccessRight: msRest.CompositeMapper = {
  serializedName: "AccessRight",
  type: {
    name: "Composite",
    className: "AccessRight",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Feature: msRest.CompositeMapper = {
  serializedName: "Feature",
  type: {
    name: "Composite",
    className: "Feature",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      availableAccessRights: {
        serializedName: "availableAccessRights",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessRight"
            }
          }
        }
      }
    }
  }
};

export const EditFeatureRequest: msRest.CompositeMapper = {
  serializedName: "EditFeatureRequest",
  type: {
    name: "Composite",
    className: "EditFeatureRequest",
    modelProperties: {
      featureId: {
        required: true,
        serializedName: "featureId",
        type: {
          name: "Number"
        }
      },
      rightsIds: {
        serializedName: "rightsIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      }
    }
  }
};

export const AccessFunction: msRest.CompositeMapper = {
  serializedName: "AccessFunction",
  type: {
    name: "Composite",
    className: "AccessFunction",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      featureId: {
        required: true,
        serializedName: "featureId",
        type: {
          name: "Number"
        }
      },
      accessRights: {
        serializedName: "accessRights",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessRight"
            }
          }
        }
      }
    }
  }
};

export const AddFunctionRequest: msRest.CompositeMapper = {
  serializedName: "AddFunctionRequest",
  type: {
    name: "Composite",
    className: "AddFunctionRequest",
    modelProperties: {
      functionName: {
        serializedName: "functionName",
        type: {
          name: "String"
        }
      },
      featureId: {
        required: true,
        serializedName: "featureId",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const EditFunctionRequest: msRest.CompositeMapper = {
  serializedName: "EditFunctionRequest",
  type: {
    name: "Composite",
    className: "EditFunctionRequest",
    modelProperties: {
      functionId: {
        required: true,
        serializedName: "functionId",
        type: {
          name: "Number"
        }
      },
      rightIds: {
        serializedName: "rightIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      }
    }
  }
};

export const Role: msRest.CompositeMapper = {
  serializedName: "Role",
  type: {
    name: "Composite",
    className: "Role",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      accessRights: {
        serializedName: "accessRights",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessRight"
            }
          }
        }
      },
      deniedRights: {
        serializedName: "deniedRights",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessRight"
            }
          }
        }
      },
      accessFunctions: {
        serializedName: "accessFunctions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessFunction"
            }
          }
        }
      }
    }
  }
};

export const EditRoleRequest: msRest.CompositeMapper = {
  serializedName: "EditRoleRequest",
  type: {
    name: "Composite",
    className: "EditRoleRequest",
    modelProperties: {
      roleId: {
        required: true,
        serializedName: "roleId",
        type: {
          name: "Number"
        }
      },
      functionIds: {
        serializedName: "functionIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      accessRightsIds: {
        serializedName: "accessRightsIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      deniedRightsIds: {
        serializedName: "deniedRightsIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      }
    }
  }
};

export const UserRights: msRest.CompositeMapper = {
  serializedName: "UserRights",
  type: {
    name: "Composite",
    className: "UserRights",
    modelProperties: {
      userId: {
        serializedName: "userId",
        type: {
          name: "String"
        }
      },
      userLogin: {
        serializedName: "userLogin",
        type: {
          name: "String"
        }
      },
      accessRights: {
        serializedName: "accessRights",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessRight"
            }
          }
        }
      },
      deniedRights: {
        serializedName: "deniedRights",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessRight"
            }
          }
        }
      },
      accessFunctions: {
        serializedName: "accessFunctions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessFunction"
            }
          }
        }
      },
      roles: {
        serializedName: "roles",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Role"
            }
          }
        }
      }
    }
  }
};

export const EditUserRightsRequest: msRest.CompositeMapper = {
  serializedName: "EditUserRightsRequest",
  type: {
    name: "Composite",
    className: "EditUserRightsRequest",
    modelProperties: {
      userId: {
        serializedName: "userId",
        type: {
          name: "String"
        }
      },
      roleIds: {
        serializedName: "roleIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      functionIds: {
        serializedName: "functionIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      accessedRightsIds: {
        serializedName: "accessedRightsIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      deniedRightsIds: {
        serializedName: "deniedRightsIds",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      }
    }
  }
};

export const CheckAccessRequest: msRest.CompositeMapper = {
  serializedName: "CheckAccessRequest",
  type: {
    name: "Composite",
    className: "CheckAccessRequest",
    modelProperties: {
      userId: {
        serializedName: "userId",
        type: {
          name: "String"
        }
      },
      accessRightNames: {
        serializedName: "accessRightNames",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};
