/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const id0: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    nullable: false,
    serializedName: "id",
    type: {
      name: "Number"
    }
  }
};
export const id1: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    nullable: true,
    serializedName: "id",
    type: {
      name: "String"
    }
  }
};
export const mask: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "mask"
  ],
  mapper: {
    nullable: true,
    serializedName: "mask",
    type: {
      name: "String"
    }
  }
};
export const page: msRest.OperationURLParameter = {
  parameterPath: "page",
  mapper: {
    required: true,
    nullable: false,
    serializedName: "page",
    type: {
      name: "Number"
    }
  }
};
export const perPage: msRest.OperationURLParameter = {
  parameterPath: "perPage",
  mapper: {
    required: true,
    nullable: false,
    serializedName: "per_page",
    type: {
      name: "Number"
    }
  }
};
