version: '3.4'

services:
   kvitkounet.web:
    image: ${DOCKER_REGISTRY}kvitkounetweb
    build:
      context: Gateway
      dockerfile: KvitkouNet.Web/Dockerfile
    depends_on:
      - adminpanel.web
      - search.web
    ports:
      - 5001:80
      - 5002:443


   usermanagement.web:
    image: ${DOCKER_REGISTRY}usersweb
    build:
      context: .
      dockerfile: UserManagement/UserManagement.Web/Dockerfile
    depends_on:
      - rabbit
    ports:
      - 5003:80

   adminpanel.web:
    image: ${DOCKER_REGISTRY}adminpanelweb
    build:
      context: ./
      dockerfile: AdminPanel/AdminPanel.Web/Dockerfile
    depends_on:
      - logging.web
      - usermanagement.web
      - rabbit
    ports:
      - 5005:80

   logging.web:
    image: ${DOCKER_REGISTRY}loggingweb
    build:
      context: ./
      dockerfile: Logging/Logging.Web/Dockerfile
    depends_on:
      - rabbit
    ports:
      - 5006:80

   tickets.web:
    image: ${DOCKER_REGISTRY}ticketsweb
    build:
      context: .
      dockerfile: TicketManagement/TicketManagement.Web/Dockerfile
    env_file:
      - host.env
    ports:
      - 5007:80
    depends_on:
      - rabbit

   search.web:
    image: ${DOCKER_REGISTRY}searchweb
    build:
      context: .
      dockerfile: Search/Search.Web/Dockerfile
    environment:
      - ConnectionStrings__ElasticSearchConnection=http://elasticsearch:9200
      - ConnectionStrings__RabbitConnection=host=rabbit
    ports:
      - 5008:80
    depends_on:
      - rabbit
      - elasticsearch

   usersettings.web:
    image: ${DOCKER_REGISTRY}usersettingsgweb
    build:
      context: ./
      dockerfile: UserSettings/UserSettings.Web/Dockerfile
    depends_on:
      - rabbit
    ports:
      - 5009:80

   rabbit:
    image: rabbitmq:management
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 15671:15671
      - 15672:15672
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

   elasticsearch:
    image: elasticsearch:6.4.3
    ports:
      - 9200:9200
      - 9300:9300

   chat.web:
    image: ${DOCKER_REGISTRY}chatweb
    build:
      context: ./
      dockerfile: Chat/Chat.Web/Dockerfile
    ports:
      - 5010:80

   security.web:
    image: ${DOCKER_REGISTRY}securityweb
    build:
      context: ./
      dockerfile: Security/Security.Web/Dockerfile
    depends_on:
      - rabbit
    ports:
      - 5011:80