/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../../../models/security";
import * as Mappers from "../../../models/security/functionsMappers";
import * as Parameters from "../../../models/security/parameters";
import { SecurityContext } from "../securityContext";

/** Class representing a Functions. */
export class Functions {
  private readonly client: SecurityContext;

  /**
   * Create a Functions.
   * @param {SecurityContext} client Reference to the service client.
   */
  constructor(client: SecurityContext) {
    this.client = client;
  }

  /**
   * @param perPage
   * @param page
   * @param [options] The optional parameters
   * @returns Promise<Models.FunctionsGetFunctionsResponse>
   */
  getFunctions(perPage: number, page: number, options?: Models.FunctionsGetFunctionsOptionalParams): Promise<Models.FunctionsGetFunctionsResponse>;
  /**
   * @param perPage
   * @param page
   * @param callback The callback
   */
  getFunctions(perPage: number, page: number, callback: msRest.ServiceCallback<Models.AccessFunction[]>): void;
  /**
   * @param perPage
   * @param page
   * @param options The optional parameters
   * @param callback The callback
   */
  getFunctions(perPage: number, page: number, options: Models.FunctionsGetFunctionsOptionalParams, callback: msRest.ServiceCallback<Models.AccessFunction[]>): void;
  getFunctions(perPage: number, page: number, options?: Models.FunctionsGetFunctionsOptionalParams | msRest.ServiceCallback<Models.AccessFunction[]>, callback?: msRest.ServiceCallback<Models.AccessFunction[]>): Promise<Models.FunctionsGetFunctionsResponse> {
    return this.client.sendOperationRequest(
      {
        perPage,
        page,
        options
      },
      getFunctionsOperationSpec,
      callback) as Promise<Models.FunctionsGetFunctionsResponse>;
  }

  /**
   * @param request
   * @param [options] The optional parameters
   * @returns Promise<Models.FunctionsAddFunctionResponse>
   */
  addFunction(request: Models.AddFunctionRequest, options?: msRest.RequestOptionsBase): Promise<Models.FunctionsAddFunctionResponse>;
  /**
   * @param request
   * @param callback The callback
   */
  addFunction(request: Models.AddFunctionRequest, callback: msRest.ServiceCallback<boolean>): void;
  /**
   * @param request
   * @param options The optional parameters
   * @param callback The callback
   */
  addFunction(request: Models.AddFunctionRequest, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<boolean>): void;
  addFunction(request: Models.AddFunctionRequest, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<boolean>, callback?: msRest.ServiceCallback<boolean>): Promise<Models.FunctionsAddFunctionResponse> {
    return this.client.sendOperationRequest(
      {
        request,
        options
      },
      addFunctionOperationSpec,
      callback) as Promise<Models.FunctionsAddFunctionResponse>;
  }

  /**
   * @param request
   * @param [options] The optional parameters
   * @returns Promise<Models.FunctionsEditFunctionResponse>
   */
  editFunction(request: Models.EditFunctionRequest, options?: msRest.RequestOptionsBase): Promise<Models.FunctionsEditFunctionResponse>;
  /**
   * @param request
   * @param callback The callback
   */
  editFunction(request: Models.EditFunctionRequest, callback: msRest.ServiceCallback<boolean>): void;
  /**
   * @param request
   * @param options The optional parameters
   * @param callback The callback
   */
  editFunction(request: Models.EditFunctionRequest, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<boolean>): void;
  editFunction(request: Models.EditFunctionRequest, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<boolean>, callback?: msRest.ServiceCallback<boolean>): Promise<Models.FunctionsEditFunctionResponse> {
    return this.client.sendOperationRequest(
      {
        request,
        options
      },
      editFunctionOperationSpec,
      callback) as Promise<Models.FunctionsEditFunctionResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.FunctionsDeleteFunctionResponse>
   */
  deleteFunction(id: number, options?: msRest.RequestOptionsBase): Promise<Models.FunctionsDeleteFunctionResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  deleteFunction(id: number, callback: msRest.ServiceCallback<boolean>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteFunction(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<boolean>): void;
  deleteFunction(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<boolean>, callback?: msRest.ServiceCallback<boolean>): Promise<Models.FunctionsDeleteFunctionResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      deleteFunctionOperationSpec,
      callback) as Promise<Models.FunctionsDeleteFunctionResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getFunctionsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/security/functions{per_page}/{page}",
  urlParameters: [
    Parameters.perPage,
    Parameters.page
  ],
  queryParameters: [
    Parameters.mask
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessFunction"
            }
          }
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};

const addFunctionOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/security/function",
  requestBody: {
    parameterPath: "request",
    mapper: {
      ...Mappers.AddFunctionRequest,
      required: true
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};

const editFunctionOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "api/security/function",
  requestBody: {
    parameterPath: "request",
    mapper: {
      ...Mappers.EditFunctionRequest,
      required: true
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};

const deleteFunctionOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/security/function/{id}",
  urlParameters: [
    Parameters.id0
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};
