/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../../../models/security";
import * as Mappers from "../../../models/security/roleOperationsMappers";
import * as Parameters from "../../../models/security/parameters";
import { SecurityContext } from "../securityContext";

/** Class representing a RoleOperations. */
export class RoleOperations {
  private readonly client: SecurityContext;

  /**
   * Create a RoleOperations.
   * @param {SecurityContext} client Reference to the service client.
   */
  constructor(client: SecurityContext) {
    this.client = client;
  }

  /**
   * @param perPage
   * @param page
   * @param [options] The optional parameters
   * @returns Promise<Models.RoleGetRolesResponse>
   */
  getRoles(perPage: number, page: number, options?: Models.RoleGetRolesOptionalParams): Promise<Models.RoleGetRolesResponse>;
  /**
   * @param perPage
   * @param page
   * @param callback The callback
   */
  getRoles(perPage: number, page: number, callback: msRest.ServiceCallback<Models.Role[]>): void;
  /**
   * @param perPage
   * @param page
   * @param options The optional parameters
   * @param callback The callback
   */
  getRoles(perPage: number, page: number, options: Models.RoleGetRolesOptionalParams, callback: msRest.ServiceCallback<Models.Role[]>): void;
  getRoles(perPage: number, page: number, options?: Models.RoleGetRolesOptionalParams | msRest.ServiceCallback<Models.Role[]>, callback?: msRest.ServiceCallback<Models.Role[]>): Promise<Models.RoleGetRolesResponse> {
    return this.client.sendOperationRequest(
      {
        perPage,
        page,
        options
      },
      getRolesOperationSpec,
      callback) as Promise<Models.RoleGetRolesResponse>;
  }

  /**
   * @param roleName
   * @param [options] The optional parameters
   * @returns Promise<Models.RoleAddRoleResponse>
   */
  addRole(roleName: string, options?: msRest.RequestOptionsBase): Promise<Models.RoleAddRoleResponse>;
  /**
   * @param roleName
   * @param callback The callback
   */
  addRole(roleName: string, callback: msRest.ServiceCallback<boolean>): void;
  /**
   * @param roleName
   * @param options The optional parameters
   * @param callback The callback
   */
  addRole(roleName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<boolean>): void;
  addRole(roleName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<boolean>, callback?: msRest.ServiceCallback<boolean>): Promise<Models.RoleAddRoleResponse> {
    return this.client.sendOperationRequest(
      {
        roleName,
        options
      },
      addRoleOperationSpec,
      callback) as Promise<Models.RoleAddRoleResponse>;
  }

  /**
   * @param request
   * @param [options] The optional parameters
   * @returns Promise<Models.RoleEditRoleResponse>
   */
  editRole(request: Models.EditRoleRequest, options?: msRest.RequestOptionsBase): Promise<Models.RoleEditRoleResponse>;
  /**
   * @param request
   * @param callback The callback
   */
  editRole(request: Models.EditRoleRequest, callback: msRest.ServiceCallback<boolean>): void;
  /**
   * @param request
   * @param options The optional parameters
   * @param callback The callback
   */
  editRole(request: Models.EditRoleRequest, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<boolean>): void;
  editRole(request: Models.EditRoleRequest, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<boolean>, callback?: msRest.ServiceCallback<boolean>): Promise<Models.RoleEditRoleResponse> {
    return this.client.sendOperationRequest(
      {
        request,
        options
      },
      editRoleOperationSpec,
      callback) as Promise<Models.RoleEditRoleResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.RoleDeleteRoleResponse>
   */
  deleteRole(id: number, options?: msRest.RequestOptionsBase): Promise<Models.RoleDeleteRoleResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  deleteRole(id: number, callback: msRest.ServiceCallback<boolean>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteRole(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<boolean>): void;
  deleteRole(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<boolean>, callback?: msRest.ServiceCallback<boolean>): Promise<Models.RoleDeleteRoleResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      deleteRoleOperationSpec,
      callback) as Promise<Models.RoleDeleteRoleResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getRolesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/security/roles/{per_page}/{page}",
  urlParameters: [
    Parameters.perPage,
    Parameters.page
  ],
  queryParameters: [
    Parameters.mask
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Role"
            }
          }
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};

const addRoleOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/security/role",
  requestBody: {
    parameterPath: "roleName",
    mapper: {
      required: true,
      nullable: false,
      serializedName: "roleName",
      type: {
        name: "String"
      }
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};

const editRoleOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "api/security/role",
  requestBody: {
    parameterPath: "request",
    mapper: {
      ...Mappers.EditRoleRequest,
      required: true
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};

const deleteRoleOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/security/role/{id}",
  urlParameters: [
    Parameters.id0
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    401: {},
    403: {},
    default: {}
  },
  serializer
};
