/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from '@azure/ms-rest-js';
import * as msRest from '@azure/ms-rest-js';


/**
 * @interface
 * An interface representing Settings.
 */
export interface Settings {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {number} backgroundColor
   */
  backgroundColor: number;
  /**
   * @member {boolean} sound
   */
  sound: boolean;
  /**
   * @member {boolean} toast
   */
  toast: boolean;
  /**
   * @member {boolean} tab
   */
  tab: boolean;
  /**
   * @member {boolean} viewTimestampsMessage
   */
  viewTimestampsMessage: boolean;
  /**
   * @member {boolean} hideChat
   */
  hideChat: boolean;
  /**
   * @member {number} historyCountsMessages
   */
  historyCountsMessages: number;
  /**
   * @member {boolean} disablePrivateMessages
   */
  disablePrivateMessages: boolean;
}

/**
 * @interface
 * An interface representing Room.
 */
export interface Room {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {boolean} isPrivat
   */
  isPrivat: boolean;
  /**
   * @member {string} [password]
   */
  password?: string;
}

/**
 * @interface
 * An interface representing Message.
 */
export interface Message {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [userId]
   */
  userId?: string;
  /**
   * @member {Date} sendedTime
   */
  sendedTime: Date;
  /**
   * @member {string} [text]
   */
  text?: string;
  /**
   * @member {boolean} isEdit
   */
  isEdit: boolean;
}

/**
 * @interface
 * An interface representing ChatOptions.
 * @extends ServiceClientOptions
 */
export interface ChatOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * Contains response data for the getUserSettings operation.
 */
export interface ChatGetUserSettingsResponse {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
}

/**
 * Contains response data for the editUserSettings operation.
 */
export interface ChatEditUserSettingsResponse {
  /**
   * The parsed response body.
   */
  body: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
}

/**
 * Contains response data for the getRooms operation.
 */
export interface RoomGetRoomsResponse {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
}

/**
 * Contains response data for the addRoom operation.
 */
export interface RoomAddRoomResponse {
  /**
   * The parsed response body.
   */
  body: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
}

/**
 * Contains response data for the searchRoom operation.
 */
export interface RoomSearchRoomResponse {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
}

/**
 * Contains response data for the getMessages operation.
 */
export interface RoomGetMessagesResponse {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
}

/**
 * Contains response data for the searchMessage operation.
 */
export interface RoomSearchMessageResponse {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
}

/**
 * Contains response data for the addMessage operation.
 */
export interface RoomAddMessageResponse {
  /**
   * The parsed response body.
   */
  body: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
}

/**
 * Contains response data for the editMessage operation.
 */
export interface RoomEditMessageResponse {
  /**
   * The parsed response body.
   */
  body: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
}

/**
 * Contains response data for the deleteMessage operation.
 */
export interface RoomDeleteMessageResponse {
  /**
   * The parsed response body.
   */
  body: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
}
