/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const Settings: msRest.CompositeMapper = {
  serializedName: "Settings",
  type: {
    name: "Composite",
    className: "Settings",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      backgroundColor: {
        required: true,
        serializedName: "backgroundColor",
        type: {
          name: "Number"
        }
      },
      sound: {
        required: true,
        serializedName: "sound",
        type: {
          name: "Boolean"
        }
      },
      toast: {
        required: true,
        serializedName: "toast",
        type: {
          name: "Boolean"
        }
      },
      tab: {
        required: true,
        serializedName: "tab",
        type: {
          name: "Boolean"
        }
      },
      viewTimestampsMessage: {
        required: true,
        serializedName: "viewTimestampsMessage",
        type: {
          name: "Boolean"
        }
      },
      hideChat: {
        required: true,
        serializedName: "hideChat",
        type: {
          name: "Boolean"
        }
      },
      historyCountsMessages: {
        required: true,
        serializedName: "historyCountsMessages",
        type: {
          name: "Number"
        }
      },
      disablePrivateMessages: {
        required: true,
        serializedName: "disablePrivateMessages",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const Room: msRest.CompositeMapper = {
  serializedName: "Room",
  type: {
    name: "Composite",
    className: "Room",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      isPrivat: {
        required: true,
        serializedName: "isPrivat",
        type: {
          name: "Boolean"
        }
      },
      password: {
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Message: msRest.CompositeMapper = {
  serializedName: "Message",
  type: {
    name: "Composite",
    className: "Message",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      userId: {
        serializedName: "userId",
        type: {
          name: "String"
        }
      },
      sendedTime: {
        required: true,
        serializedName: "sendedTime",
        type: {
          name: "DateTime"
        }
      },
      text: {
        serializedName: "text",
        type: {
          name: "String"
        }
      },
      isEdit: {
        required: true,
        serializedName: "isEdit",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};
