/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const historyCountsMessages: msRest.OperationURLParameter = {
  parameterPath: "historyCountsMessages",
  mapper: {
    required: true,
    nullable: false,
    serializedName: "historyCountsMessages",
    type: {
      name: "Number"
    }
  }
};
export const mid: msRest.OperationURLParameter = {
  parameterPath: "mid",
  mapper: {
    required: true,
    nullable: true,
    serializedName: "mid",
    type: {
      name: "String"
    }
  }
};
export const rid: msRest.OperationURLParameter = {
  parameterPath: "rid",
  mapper: {
    required: true,
    nullable: true,
    serializedName: "rid",
    type: {
      name: "String"
    }
  }
};
export const template: msRest.OperationURLParameter = {
  parameterPath: "template",
  mapper: {
    required: true,
    nullable: true,
    serializedName: "template",
    type: {
      name: "String"
    }
  }
};
export const uid: msRest.OperationURLParameter = {
  parameterPath: "uid",
  mapper: {
    required: true,
    nullable: true,
    serializedName: "uid",
    type: {
      name: "String"
    }
  }
};
