// <auto-generated />
using System;
using Dashboard.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard.Data.Migrations
{
    [DbContext(typeof(DashboardContext))]
    partial class DashboardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Dashboard.Data.DbModels.NewsDb", b =>
                {
                    b.Property<string>("NewsId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("EventLink");

                    b.Property<int>("Status");

                    b.Property<int>("TypeEvent");

                    b.HasKey("NewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Dashboard.Data.DbModels.TicketInfoDb", b =>
                {
                    b.Property<string>("TicketId");

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("NewsDbsNewsId");

                    b.Property<decimal?>("Price");

                    b.HasKey("TicketId");

                    b.HasIndex("NewsDbsNewsId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Dashboard.Data.DbModels.TicketInfoDb", b =>
                {
                    b.HasOne("Dashboard.Data.DbModels.NewsDb", "NewsDbs")
                        .WithMany()
                        .HasForeignKey("NewsDbsNewsId");

                    b.HasOne("Dashboard.Data.DbModels.NewsDb")
                        .WithOne("Ticket")
                        .HasForeignKey("Dashboard.Data.DbModels.TicketInfoDb", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
