// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketManagement.Data.Context;

namespace TicketManagement.Data.Migrations
{
    [DbContext(typeof(TicketContext))]
    partial class TicketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TicketManagement.Data.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Flat");

                    b.Property<string>("House");

                    b.Property<string>("Street");

                    b.HasKey("AddressId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("TicketManagement.Data.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalData");

                    b.Property<string>("EventLink");

                    b.Property<bool>("Free");

                    b.Property<string>("LocationEventAddressId");

                    b.Property<string>("Name");

                    b.Property<string>("PaymentSystems");

                    b.Property<decimal>("Price");

                    b.Property<string>("SellerAdressAddressId");

                    b.Property<string>("SellerPhone");

                    b.Property<int>("Status");

                    b.Property<string>("TimeActual");

                    b.Property<int>("TypeEvent");

                    b.Property<string>("UserInfoId");

                    b.HasKey("TicketId");

                    b.HasIndex("LocationEventAddressId");

                    b.HasIndex("SellerAdressAddressId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketManagement.Data.Models.UserInfo", b =>
                {
                    b.Property<string>("UserInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<double>("Rating");

                    b.Property<string>("TicketId");

                    b.HasKey("UserInfoId");

                    b.HasIndex("TicketId");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("TicketManagement.Data.Models.Ticket", b =>
                {
                    b.HasOne("TicketManagement.Data.Models.Address", "LocationEvent")
                        .WithMany()
                        .HasForeignKey("LocationEventAddressId");

                    b.HasOne("TicketManagement.Data.Models.Address", "SellerAdress")
                        .WithMany()
                        .HasForeignKey("SellerAdressAddressId");

                    b.HasOne("TicketManagement.Data.Models.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("TicketManagement.Data.Models.UserInfo", b =>
                {
                    b.HasOne("TicketManagement.Data.Models.Ticket")
                        .WithMany("RespondedUsers")
                        .HasForeignKey("TicketId");
                });
#pragma warning restore 612, 618
        }
    }
}
